
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.parker.retargetableassembler.tokenizer.inter.cup;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 20;
  public static final int INPUT = 2;
  public static final int ELSE = 9;
  public static final int PLUS = 19;
  public static final int THEN = 8;
  public static final int END = 5;
  public static final int FI = 10;
  public static final int ERROR = 11;
  public static final int IF = 7;
  public static final int ID = 23;
  public static final int LE = 16;
  public static final int COMMA = 12;
  public static final int NUMBER = 24;
  public static final int EOF = 0;
  public static final int DIV = 21;
  public static final int MINUS = 18;
  public static final int ARGUMENTS = 6;
  public static final int error = 1;
  public static final int EQ = 15;
  public static final int FUNCTIONS = 3;
  public static final int LEQ = 17;
  public static final int RPAR = 14;
  public static final int OUTPUT = 4;
  public static final int LPAR = 13;
  public static final int UMINUS = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INPUT",
  "FUNCTIONS",
  "OUTPUT",
  "END",
  "ARGUMENTS",
  "IF",
  "THEN",
  "ELSE",
  "FI",
  "ERROR",
  "COMMA",
  "LPAR",
  "RPAR",
  "EQ",
  "LE",
  "LEQ",
  "MINUS",
  "PLUS",
  "TIMES",
  "DIV",
  "UMINUS",
  "ID",
  "NUMBER"
  };
}

