// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/java/org/parker/retargetableassembler/pipe/lex/jflex/AssemblerScanner.jflex

package org.parker.retargetableassembler.pipe.lex.jflex;
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright (C) 2001       Gerwin Klein <lsf@jflex.de>                    *
 * Copyright (C) 2001       Bernhard Rumpe <rumpe@in.tum.de>               *
 * All rights reserved.                                                    *
 *                                                                         *
 * License: BSD                                                            *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */


import java.io.File;
import java.util.Iterator;
import org.parker.retargetableassembler.pipe.lex.cup.AssemblerSym;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class AssemblerScanner implements AssemblerSym, Iterator<LexSymbol> {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHARLITERAL = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\10\u2f00\31\u1f00\1\u0100\1\u3000\1\u3100\1\u0100\1\u3200"+
    "\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\3\u1f00"+
    "\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\3\u1f00\1\u3f00\1\u4000"+
    "\4\u1f00\1\u4100\11\u1f00\3\u0100\1\u4200\1\u4300\13\u1f00\4\u0100"+
    "\1\u4400\63\u1f00\2\u0100\1\u4500\4\u1f00\1\u4600\100\u1f00\1\u4700"+
    "\40\u1f00\1\u4800\1\u4900\1\u1f00\1\u4a00\1\u4b00\1\u4c00\1\u4d00"+
    "\26\u1f00\1\u4e00\21\u1f00\246\u0100\1\u4f00\20\u0100\1\u5000\1\u5100"+
    "\77\u1f00\2\u0100\1\u5100\u0b05\u1f00\1\u5200\1\u5300\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\16\0\4\6"+
    "\1\1\1\7\1\10\1\6\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\6\1\45\2\46\1\47\1\50\1\51\5\11\1\52"+
    "\5\11\1\53\1\54\1\55\1\56\2\11\1\57\2\11"+
    "\1\60\1\61\1\62\1\63\1\11\1\6\1\64\1\65"+
    "\1\46\1\47\1\66\1\67\5\11\1\70\1\11\1\71"+
    "\3\11\1\72\1\73\1\74\1\75\2\11\1\57\2\11"+
    "\1\76\1\77\1\100\1\101\6\0\1\102\32\0\2\6"+
    "\4\11\4\6\1\11\2\6\1\0\7\6\1\11\4\6"+
    "\1\11\5\6\27\11\1\6\37\11\1\6\u01ca\11\4\6"+
    "\14\11\16\6\5\11\7\6\1\11\1\6\1\11\21\6"+
    "\160\0\5\11\1\6\2\11\2\6\4\11\10\6\1\11"+
    "\1\6\3\11\1\6\1\11\1\6\24\11\1\6\123\11"+
    "\1\6\213\11\1\6\5\0\2\6\236\11\11\6\46\11"+
    "\2\6\1\11\7\6\47\11\7\6\1\11\1\6\55\0"+
    "\1\6\1\0\1\6\2\0\1\6\2\0\1\6\1\0"+
    "\10\6\33\11\5\6\3\11\15\6\5\0\6\6\1\11"+
    "\4\6\13\0\5\6\53\11\37\0\4\6\2\11\1\0"+
    "\143\11\1\6\1\11\10\0\1\6\6\0\2\11\2\0"+
    "\1\6\4\0\2\11\12\0\3\11\2\6\1\11\17\6"+
    "\1\0\1\11\1\0\36\11\33\0\2\6\131\11\13\0"+
    "\1\11\16\6\12\0\41\11\11\0\2\11\4\6\1\11"+
    "\5\6\26\11\4\0\1\11\11\0\1\11\3\0\1\11"+
    "\5\0\22\6\31\11\3\0\104\6\1\11\1\6\13\11"+
    "\67\6\33\0\1\6\4\0\66\11\3\0\1\11\22\0"+
    "\1\11\7\0\12\11\2\0\2\6\12\0\1\6\7\11"+
    "\1\6\7\11\1\6\3\0\1\6\10\11\2\6\2\11"+
    "\2\6\26\11\1\6\7\11\1\6\1\11\3\6\4\11"+
    "\2\6\1\0\1\11\7\0\2\6\2\0\2\6\3\0"+
    "\1\11\10\6\1\0\4\6\2\11\1\6\3\11\2\0"+
    "\2\6\12\0\4\11\7\6\1\11\5\6\3\0\1\6"+
    "\6\11\4\6\2\11\2\6\26\11\1\6\7\11\1\6"+
    "\2\11\1\6\2\11\1\6\2\11\2\6\1\0\1\6"+
    "\5\0\4\6\2\0\2\6\3\0\3\6\1\0\7\6"+
    "\4\11\1\6\1\11\7\6\14\0\3\11\1\0\13\6"+
    "\3\0\1\6\11\11\1\6\3\11\1\6\26\11\1\6"+
    "\7\11\1\6\2\11\1\6\5\11\2\6\1\0\1\11"+
    "\10\0\1\6\3\0\1\6\3\0\2\6\1\11\17\6"+
    "\2\11\2\0\2\6\12\0\1\6\1\11\17\6\3\0"+
    "\1\6\10\11\2\6\2\11\2\6\26\11\1\6\7\11"+
    "\1\6\2\11\1\6\5\11\2\6\1\0\1\11\7\0"+
    "\2\6\2\0\2\6\3\0\10\6\2\0\4\6\2\11"+
    "\1\6\3\11\2\0\2\6\12\0\1\6\1\11\20\6"+
    "\1\0\1\11\1\6\6\11\3\6\3\11\1\6\4\11"+
    "\3\6\2\11\1\6\1\11\1\6\2\11\3\6\2\11"+
    "\3\6\3\11\3\6\14\11\4\6\5\0\3\6\3\0"+
    "\1\6\4\0\2\6\1\11\6\6\1\0\16\6\12\0"+
    "\11\6\1\11\7\6\3\0\1\6\10\11\1\6\3\11"+
    "\1\6\27\11\1\6\12\11\1\6\5\11\3\6\1\11"+
    "\7\0\1\6\3\0\1\6\4\0\7\6\2\0\1\6"+
    "\2\11\6\6\2\11\2\0\2\6\12\0\22\6\2\0"+
    "\1\6\10\11\1\6\3\11\1\6\27\11\1\6\12\11"+
    "\1\6\5\11\2\6\1\0\1\11\7\0\1\6\3\0"+
    "\1\6\4\0\7\6\2\0\7\6\1\11\1\6\2\11"+
    "\2\0\2\6\12\0\1\6\2\11\17\6\2\0\1\6"+
    "\10\11\1\6\3\11\1\6\51\11\2\6\1\11\7\0"+
    "\1\6\3\0\1\6\4\0\1\11\10\6\1\0\10\6"+
    "\2\11\2\0\2\6\12\0\12\6\6\11\2\6\2\0"+
    "\1\6\22\11\3\6\30\11\1\6\11\11\1\6\1\11"+
    "\2\6\7\11\3\6\1\0\4\6\6\0\1\6\1\0"+
    "\1\6\10\0\22\6\2\0\15\6\60\11\1\0\2\11"+
    "\7\0\4\6\10\11\10\0\1\6\12\0\47\6\2\11"+
    "\1\6\1\11\2\6\2\11\1\6\1\11\2\6\1\11"+
    "\6\6\4\11\1\6\7\11\1\6\3\11\1\6\1\11"+
    "\1\6\1\11\2\6\2\11\1\6\4\11\1\0\2\11"+
    "\6\0\1\6\2\0\1\11\2\6\5\11\1\6\1\11"+
    "\1\6\6\0\2\6\12\0\2\6\4\11\40\6\1\11"+
    "\27\6\2\0\6\6\12\0\13\6\1\0\1\6\1\0"+
    "\1\6\1\0\4\6\2\0\10\11\1\6\44\11\4\6"+
    "\24\0\1\6\2\0\5\11\13\0\1\6\44\0\11\6"+
    "\1\0\71\6\53\11\24\0\1\11\12\0\6\6\6\11"+
    "\4\0\4\11\3\0\1\11\3\0\2\11\7\0\3\11"+
    "\4\0\15\11\14\0\1\11\17\0\2\6\46\11\1\6"+
    "\1\11\5\6\1\11\2\6\53\11\1\6\115\11\1\6"+
    "\4\11\2\6\7\11\1\6\1\11\1\6\4\11\2\6"+
    "\51\11\1\6\4\11\2\6\41\11\1\6\4\11\2\6"+
    "\7\11\1\6\1\11\1\6\4\11\2\6\17\11\1\6"+
    "\71\11\1\6\4\11\2\6\103\11\2\6\3\0\40\6"+
    "\20\11\20\6\125\11\14\6\u016c\11\2\6\21\11\1\6"+
    "\32\11\5\6\113\11\3\6\3\11\17\6\15\11\1\6"+
    "\4\11\3\0\13\6\22\11\3\0\13\6\22\11\2\0"+
    "\14\6\15\11\1\6\3\11\1\6\2\0\14\6\64\11"+
    "\40\0\3\6\1\11\3\6\2\11\1\0\2\6\12\0"+
    "\41\6\3\0\2\6\12\0\6\6\130\11\10\6\51\11"+
    "\1\0\1\11\5\6\106\11\12\6\35\11\3\6\14\0"+
    "\4\6\14\0\12\6\12\0\36\11\2\6\5\11\13\6"+
    "\54\11\4\6\21\0\7\11\2\0\6\6\12\0\46\6"+
    "\27\11\5\0\4\6\65\11\12\0\1\6\35\0\2\6"+
    "\13\0\6\6\12\0\15\6\1\11\130\6\5\0\57\11"+
    "\21\0\7\11\4\6\12\0\21\6\11\0\14\6\3\0"+
    "\36\11\15\0\2\11\12\0\54\11\16\0\14\6\44\11"+
    "\24\0\10\6\12\0\3\6\3\11\12\0\44\11\122\6"+
    "\3\0\1\6\25\0\4\11\1\0\4\11\3\0\2\11"+
    "\11\6\300\11\47\0\25\6\4\0\26\11\2\6\6\11"+
    "\2\6\46\11\2\6\6\11\2\6\10\11\1\6\1\11"+
    "\1\6\1\11\1\6\1\11\1\6\37\11\2\6\65\11"+
    "\1\6\7\11\1\6\1\11\3\6\3\11\1\6\7\11"+
    "\3\6\4\11\2\6\6\11\4\6\15\11\5\6\3\11"+
    "\1\6\7\11\16\6\5\0\30\6\2\3\5\0\20\6"+
    "\2\11\23\6\1\11\13\6\5\0\5\6\6\0\1\6"+
    "\1\11\15\6\1\11\20\6\15\11\3\6\33\11\25\6"+
    "\15\0\4\6\1\0\3\6\14\0\21\6\1\11\4\6"+
    "\1\11\2\6\12\11\1\6\1\11\3\6\5\11\6\6"+
    "\1\11\1\6\1\11\1\6\1\11\1\6\4\11\1\6"+
    "\13\11\2\6\4\11\5\6\5\11\4\6\1\11\21\6"+
    "\51\11\u0177\6\57\11\1\6\57\11\1\6\205\11\6\6"+
    "\4\11\3\0\2\11\14\6\46\11\1\6\1\11\5\6"+
    "\1\11\2\6\70\11\7\6\1\11\17\6\1\0\27\11"+
    "\11\6\7\11\1\6\7\11\1\6\7\11\1\6\7\11"+
    "\1\6\7\11\1\6\7\11\1\6\7\11\1\6\7\11"+
    "\1\6\40\0\57\6\1\11\325\6\3\11\31\6\11\11"+
    "\6\0\1\6\5\11\2\6\5\11\4\6\126\11\2\6"+
    "\2\0\2\6\3\11\1\6\132\11\1\6\4\11\5\6"+
    "\51\11\3\6\136\11\21\6\33\11\65\6\306\11\112\6"+
    "\315\11\63\6\215\11\103\6\56\11\2\6\15\11\3\6"+
    "\20\11\12\0\2\11\24\6\57\11\1\0\4\6\12\0"+
    "\1\6\31\11\7\6\1\0\120\11\2\0\45\6\11\11"+
    "\2\6\147\11\2\6\4\11\1\6\4\11\14\6\13\11"+
    "\115\6\12\11\1\0\3\11\1\0\4\11\1\0\27\11"+
    "\5\0\20\6\1\11\7\6\64\11\14\6\2\0\62\11"+
    "\21\0\13\6\12\0\6\6\22\0\6\11\3\6\1\11"+
    "\4\6\12\0\34\11\10\0\2\6\27\11\15\0\14\6"+
    "\35\11\3\6\4\0\57\11\16\0\16\6\1\11\12\0"+
    "\46\6\51\11\16\0\11\6\3\11\1\0\10\11\2\0"+
    "\2\6\12\0\6\6\27\11\3\6\1\11\1\0\4\6"+
    "\60\11\1\0\1\11\3\0\2\11\2\0\5\11\2\0"+
    "\1\11\1\0\1\11\30\6\3\11\2\6\13\11\5\0"+
    "\2\6\3\11\2\0\12\6\6\11\2\6\6\11\2\6"+
    "\6\11\11\6\7\11\1\6\7\11\221\6\43\11\10\0"+
    "\1\6\2\0\2\6\12\0\6\6\244\11\14\6\27\11"+
    "\4\6\61\11\4\6\u0100\3\156\11\2\6\152\11\46\6"+
    "\7\11\14\6\5\11\5\6\1\11\1\0\12\11\1\6"+
    "\15\11\1\6\5\11\1\6\1\11\1\6\2\11\1\6"+
    "\2\11\1\6\154\11\41\6\153\11\22\6\100\11\2\6"+
    "\66\11\50\6\15\11\3\6\20\0\20\6\7\0\14\6"+
    "\2\11\30\6\3\11\31\6\1\11\6\6\5\11\1\6"+
    "\207\11\2\6\1\0\4\6\1\11\13\6\12\0\7\6"+
    "\32\11\4\6\1\11\1\6\32\11\13\6\131\11\3\6"+
    "\6\11\2\6\6\11\2\6\6\11\2\6\3\11\3\6"+
    "\2\11\3\6\2\11\22\6\3\0\4\6\14\11\1\6"+
    "\32\11\1\6\23\11\1\6\2\11\1\6\17\11\2\6"+
    "\16\11\42\6\173\11\105\6\65\11\210\6\1\0\202\6"+
    "\35\11\3\6\61\11\57\6\37\11\21\6\33\11\65\6"+
    "\36\11\2\6\44\11\4\6\10\11\1\6\5\11\52\6"+
    "\236\11\2\6\12\0\126\6\6\11\2\6\1\11\1\6"+
    "\54\11\1\6\2\11\3\6\1\11\2\6\27\11\252\6"+
    "\26\11\12\6\32\11\106\6\70\11\6\6\2\11\100\6"+
    "\1\11\3\0\1\6\2\0\5\6\4\0\4\11\1\6"+
    "\3\11\1\6\33\11\4\6\3\0\4\6\1\0\40\6"+
    "\35\11\203\6\66\11\12\6\26\11\12\6\23\11\215\6"+
    "\111\11\267\6\3\0\65\11\17\0\37\6\12\0\20\6"+
    "\3\0\55\11\13\0\2\6\1\0\22\6\31\11\7\6"+
    "\12\0\6\6\3\0\44\11\16\0\1\6\12\0\100\6"+
    "\3\0\60\11\16\0\4\11\13\6\12\0\246\6\53\11"+
    "\15\0\10\6\12\0\66\6\157\11\221\6\143\11\235\6"+
    "\57\11\321\6\71\11\307\6\105\11\13\6\1\11\56\0"+
    "\20\6\4\0\15\11\140\6\2\11\u0163\6\5\0\3\6"+
    "\26\0\2\6\7\0\36\6\4\0\224\6\3\0\273\6"+
    "\125\11\1\6\107\11\1\6\2\11\2\6\1\11\2\6"+
    "\2\11\2\6\4\11\1\6\14\11\1\6\1\11\1\6"+
    "\7\11\1\6\101\11\1\6\4\11\2\6\10\11\1\6"+
    "\7\11\1\6\34\11\1\6\4\11\1\6\5\11\1\6"+
    "\1\11\3\6\7\11\1\6\u0154\11\2\6\31\11\1\6"+
    "\31\11\1\6\37\11\1\6\31\11\1\6\37\11\1\6"+
    "\31\11\1\6\37\11\1\6\31\11\1\6\37\11\1\6"+
    "\31\11\1\6\10\11\2\6\62\0\4\11\1\6\33\11"+
    "\1\6\2\11\1\6\1\11\2\6\1\11\1\6\12\11"+
    "\1\6\4\11\1\6\1\11\1\6\1\11\6\6\1\11"+
    "\4\6\1\11\1\6\1\11\1\6\1\11\1\6\3\11"+
    "\1\6\2\11\1\6\1\11\2\6\1\11\1\6\1\11"+
    "\1\6\1\11\1\6\1\11\1\6\1\11\1\6\2\11"+
    "\1\6\1\11\2\6\4\11\1\6\7\11\1\6\4\11"+
    "\1\6\4\11\1\6\1\11\1\6\12\11\1\6\21\11"+
    "\5\6\3\11\1\6\5\11\1\6\21\11\104\6\327\11"+
    "\51\6\65\11\13\6\336\11\343\6\1\0\36\6\140\0"+
    "\200\6\360\0\20\6";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[21504];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\2\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\2\6\1\31\1\32\1\33\2\6\1\34\1\35"+
    "\1\36\1\37\1\40\2\41\1\42\2\1\2\43\1\1"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\0\1\54\1\55\1\0\1\56\1\57\4\60\1\55"+
    "\1\61\1\0\1\62\1\63\1\0\1\64\1\65\1\66"+
    "\1\67\1\70\2\6\1\71\2\6\1\72\1\73\1\74"+
    "\1\75\1\76\2\77\1\100\1\101\1\102\1\103\1\104"+
    "\1\105\1\106\12\74\2\0\2\56\1\107\2\60\1\0"+
    "\1\55\2\110\1\111\1\112\1\113\4\6\1\77\1\114"+
    "\1\115\1\116\2\0\1\117\1\120\1\121\1\122\1\123"+
    "\1\124\1\0\2\60\1\125\1\110\1\126\1\6\1\127"+
    "\1\6\1\0\2\60\1\110\1\130\1\0\2\60\1\110"+
    "\1\0\2\60\1\110\1\0\2\60\1\110\1\0\2\60"+
    "\1\110\1\0\2\60\1\110\1\131\2\60\1\0\2\60"+
    "\1\0\2\60\1\0\2\60\1\0\2\60\1\0\2\60"+
    "\1\0\1\60\1\55\1\0\1\55\1\0\4\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[198];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\103\0\206\0\311\0\311\0\u010c\0\u014f\0\311"+
    "\0\u0192\0\u01d5\0\u0218\0\311\0\311\0\311\0\u025b\0\u029e"+
    "\0\311\0\u02e1\0\u0324\0\u0367\0\u03aa\0\u03ed\0\311\0\311"+
    "\0\u0430\0\u0473\0\u04b6\0\311\0\u04f9\0\u053c\0\311\0\311"+
    "\0\u057f\0\u05c2\0\u0605\0\311\0\u0648\0\311\0\311\0\u068b"+
    "\0\311\0\u06ce\0\311\0\u0711\0\u0754\0\311\0\u0797\0\u07da"+
    "\0\311\0\311\0\311\0\311\0\311\0\311\0\311\0\311"+
    "\0\u081d\0\311\0\u0860\0\u08a3\0\u08e6\0\311\0\u0929\0\u096c"+
    "\0\u09af\0\u09f2\0\u0a35\0\311\0\u0a78\0\311\0\311\0\u0abb"+
    "\0\u0afe\0\311\0\311\0\311\0\u0b41\0\u0b84\0\u0bc7\0\311"+
    "\0\u0c0a\0\u0c4d\0\311\0\311\0\311\0\311\0\311\0\u0c90"+
    "\0\u0cd3\0\311\0\311\0\311\0\311\0\311\0\311\0\311"+
    "\0\u0d16\0\u0d59\0\u0d9c\0\u0ddf\0\u0e22\0\u0e65\0\u0ea8\0\u0eeb"+
    "\0\u0f2e\0\u0f71\0\u0fb4\0\u0ff7\0\311\0\u103a\0\311\0\u107d"+
    "\0\u10c0\0\u1103\0\u1146\0\u1189\0\u11cc\0\311\0\311\0\u120f"+
    "\0\u1252\0\u1295\0\u12d8\0\u131b\0\311\0\311\0\311\0\311"+
    "\0\u0ddf\0\u135e\0\311\0\311\0\311\0\311\0\311\0\311"+
    "\0\u13a1\0\u13e4\0\u1427\0\311\0\u146a\0\311\0\u14ad\0\u0192"+
    "\0\u14f0\0\u1533\0\u1576\0\u15b9\0\u15fc\0\u0192\0\u163f\0\u1682"+
    "\0\u16c5\0\u1708\0\u174b\0\u178e\0\u17d1\0\u1814\0\u1857\0\u189a"+
    "\0\u18dd\0\u1920\0\u1963\0\u19a6\0\u19e9\0\u1a2c\0\u1a6f\0\u1ab2"+
    "\0\u1af5\0\u1b38\0\311\0\u1b7b\0\u1bbe\0\u1c01\0\u1c44\0\u1c87"+
    "\0\u1cca\0\u1d0d\0\u1d50\0\u1d93\0\u1dd6\0\u1e19\0\u1e5c\0\u1e9f"+
    "\0\u1ee2\0\u1f25\0\u1f68\0\u1fab\0\u1fee\0\u2031\0\u2031\0\u2074"+
    "\0\u20b7\0\u20fa\0\u213d\0\u2180\0\u21c3\0\u2206";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[198];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\4\1\5\1\6\1\4\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\11\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\4\11\1\35\3\11"+
    "\1\36\2\11\1\37\1\4\1\40\1\41\3\11\1\42"+
    "\4\11\1\43\1\11\1\44\1\45\1\46\1\47\1\4"+
    "\2\50\1\51\2\50\1\52\2\50\1\53\50\50\1\54"+
    "\21\50\2\55\1\56\2\55\1\57\6\55\1\4\44\55"+
    "\1\60\21\55\105\0\1\6\2\0\1\6\137\0\1\61"+
    "\40\0\1\11\10\0\1\11\13\0\12\11\6\0\13\11"+
    "\4\0\12\11\4\0\1\11\42\0\1\62\53\0\1\63"+
    "\26\0\1\64\102\0\1\65\60\0\1\66\21\0\1\67"+
    "\62\0\1\70\4\0\1\71\12\0\1\72\65\0\12\73"+
    "\63\0\1\74\4\0\1\75\15\0\1\76\63\0\1\73"+
    "\1\0\1\77\1\100\2\101\4\102\2\103\10\0\1\104"+
    "\1\105\1\106\1\107\4\0\1\110\6\0\1\105\1\106"+
    "\1\107\35\0\1\73\1\0\12\26\10\0\1\104\1\105"+
    "\1\106\1\107\13\0\1\105\1\106\1\107\53\0\1\111"+
    "\1\112\102\0\1\113\102\0\1\114\1\115\37\0\1\11"+
    "\10\0\1\11\13\0\12\11\6\0\1\116\12\11\4\0"+
    "\12\11\4\0\2\11\10\0\1\11\13\0\12\11\6\0"+
    "\6\11\1\117\4\11\4\0\12\11\4\0\1\11\42\0"+
    "\1\120\40\0\1\11\10\0\1\11\13\0\12\11\6\0"+
    "\13\11\4\0\1\121\11\11\4\0\2\11\10\0\1\11"+
    "\13\0\12\11\6\0\13\11\4\0\6\11\1\122\3\11"+
    "\4\0\1\11\42\0\1\123\34\0\1\124\3\0\2\50"+
    "\1\0\2\50\1\0\2\50\1\0\50\50\1\0\21\50"+
    "\2\0\1\51\100\0\2\125\4\0\2\125\1\126\3\125"+
    "\1\127\10\125\4\130\4\131\24\125\1\132\3\125\1\133"+
    "\1\125\1\134\1\125\1\135\1\136\1\125\1\137\5\125"+
    "\15\0\1\140\70\0\1\56\100\0\2\125\4\0\2\125"+
    "\1\141\3\125\1\142\10\125\4\143\4\144\24\125\1\145"+
    "\3\125\1\146\1\125\1\147\1\125\1\150\1\151\1\125"+
    "\1\152\5\125\27\0\1\153\101\0\12\73\10\0\1\104"+
    "\1\105\1\106\14\0\1\105\1\106\13\0\17\74\1\154"+
    "\63\74\2\75\1\155\2\75\1\156\75\75\23\0\1\73"+
    "\1\0\1\77\1\100\2\101\4\102\2\103\10\0\1\104"+
    "\1\105\1\106\1\157\13\0\1\105\1\106\1\157\35\0"+
    "\1\73\1\0\10\102\2\103\10\0\1\104\1\105\1\106"+
    "\1\157\13\0\1\105\1\106\1\157\35\0\1\73\1\0"+
    "\10\160\2\103\10\0\1\104\1\105\1\106\1\157\13\0"+
    "\1\105\1\106\1\157\35\0\1\73\1\0\10\161\2\103"+
    "\10\0\1\104\1\105\1\106\1\157\13\0\1\105\1\106"+
    "\1\157\35\0\1\73\1\0\12\103\10\0\1\104\1\105"+
    "\1\106\14\0\1\105\1\106\33\0\1\162\1\0\1\162"+
    "\2\0\12\163\71\0\1\164\11\165\6\0\5\165\12\0"+
    "\4\165\55\0\1\166\102\0\1\167\1\170\37\0\1\11"+
    "\10\0\1\11\13\0\12\11\6\0\5\11\1\171\5\11"+
    "\4\0\12\11\4\0\2\11\10\0\1\11\13\0\12\11"+
    "\6\0\11\11\1\172\1\11\4\0\12\11\4\0\2\11"+
    "\10\0\1\11\13\0\12\11\6\0\13\11\4\0\4\11"+
    "\1\173\5\11\4\0\2\11\10\0\1\11\13\0\12\11"+
    "\6\0\13\11\4\0\11\11\1\174\4\0\1\11\25\0"+
    "\10\131\73\0\10\175\62\0\1\176\102\0\1\177\102\0"+
    "\1\200\10\0\10\201\62\0\1\200\10\0\10\202\62\0"+
    "\1\203\102\0\1\204\102\0\1\205\102\0\1\206\102\0"+
    "\1\207\102\0\1\210\117\0\1\211\51\0\17\74\1\154"+
    "\4\74\1\155\56\74\2\0\1\155\123\0\1\73\1\0"+
    "\10\212\2\103\10\0\1\104\1\105\1\106\1\157\13\0"+
    "\1\105\1\106\1\157\35\0\1\73\1\0\10\213\2\103"+
    "\10\0\1\104\1\105\1\106\1\157\13\0\1\105\1\106"+
    "\1\157\37\0\12\163\71\0\12\163\10\0\1\104\1\0"+
    "\1\106\15\0\1\106\40\0\1\164\11\165\6\0\5\165"+
    "\1\214\11\0\4\165\1\214\37\0\12\215\6\0\5\215"+
    "\1\214\11\0\4\215\1\214\54\0\1\216\40\0\1\11"+
    "\10\0\1\11\13\0\12\11\6\0\7\11\1\217\3\11"+
    "\4\0\12\11\4\0\2\11\10\0\1\11\13\0\12\11"+
    "\6\0\3\11\1\220\7\11\4\0\12\11\4\0\2\11"+
    "\10\0\1\11\13\0\12\11\6\0\13\11\4\0\7\11"+
    "\1\221\2\11\4\0\2\11\10\0\1\11\13\0\12\11"+
    "\6\0\13\11\4\0\2\11\1\220\7\11\4\0\1\11"+
    "\14\0\1\200\122\0\1\222\71\0\1\73\1\0\10\223"+
    "\2\103\10\0\1\104\1\105\1\106\1\157\13\0\1\105"+
    "\1\106\1\157\35\0\1\73\1\0\10\224\2\103\10\0"+
    "\1\104\1\105\1\106\1\157\13\0\1\105\1\106\1\157"+
    "\37\0\12\225\6\0\5\225\1\214\11\0\4\225\1\214"+
    "\12\0\1\11\10\0\1\11\13\0\12\11\6\0\3\11"+
    "\1\226\7\11\4\0\12\11\4\0\2\11\10\0\1\11"+
    "\13\0\12\11\6\0\13\11\4\0\2\11\1\226\7\11"+
    "\4\0\1\11\31\0\1\227\74\0\1\73\1\0\10\230"+
    "\2\103\10\0\1\104\1\105\1\106\1\157\13\0\1\105"+
    "\1\106\1\157\35\0\1\73\1\0\10\231\2\103\10\0"+
    "\1\104\1\105\1\106\1\157\13\0\1\105\1\106\1\157"+
    "\37\0\12\232\6\0\5\232\1\214\11\0\4\232\1\214"+
    "\47\0\1\233\70\0\1\73\1\0\10\234\2\103\10\0"+
    "\1\104\1\105\1\106\1\157\13\0\1\105\1\106\1\157"+
    "\35\0\1\73\1\0\10\235\2\103\10\0\1\104\1\105"+
    "\1\106\1\157\13\0\1\105\1\106\1\157\37\0\12\236"+
    "\6\0\5\236\1\214\11\0\4\236\1\214\42\0\1\237"+
    "\75\0\1\73\1\0\10\240\2\103\10\0\1\104\1\105"+
    "\1\106\1\157\13\0\1\105\1\106\1\157\35\0\1\73"+
    "\1\0\10\241\2\103\10\0\1\104\1\105\1\106\1\157"+
    "\13\0\1\105\1\106\1\157\37\0\12\242\6\0\5\242"+
    "\1\214\11\0\4\242\1\214\45\0\1\243\72\0\1\73"+
    "\1\0\10\244\2\103\10\0\1\104\1\105\1\106\1\157"+
    "\13\0\1\105\1\106\1\157\35\0\1\73\1\0\10\245"+
    "\2\103\10\0\1\104\1\105\1\106\1\157\13\0\1\105"+
    "\1\106\1\157\37\0\12\246\6\0\5\246\1\214\11\0"+
    "\4\246\1\214\43\0\1\247\74\0\1\73\1\0\10\250"+
    "\2\103\10\0\1\104\1\105\1\106\1\157\13\0\1\105"+
    "\1\106\1\157\35\0\1\73\1\0\10\251\2\103\10\0"+
    "\1\104\1\105\1\106\1\157\13\0\1\105\1\106\1\157"+
    "\37\0\12\252\6\0\5\252\1\214\11\0\4\252\1\214"+
    "\47\0\1\253\70\0\1\73\1\0\10\254\2\103\10\0"+
    "\1\104\1\105\1\106\1\157\13\0\1\105\1\106\1\157"+
    "\35\0\1\73\1\0\10\255\2\103\10\0\1\104\1\105"+
    "\1\106\1\157\13\0\1\105\1\106\1\157\37\0\12\256"+
    "\6\0\5\256\1\214\11\0\4\256\1\214\35\0\1\73"+
    "\1\0\10\257\2\103\10\0\1\104\1\105\1\106\1\157"+
    "\13\0\1\105\1\106\1\157\35\0\1\73\1\0\10\260"+
    "\2\103\10\0\1\104\1\105\1\106\1\157\13\0\1\105"+
    "\1\106\1\157\37\0\12\261\6\0\5\261\1\214\11\0"+
    "\4\261\1\214\35\0\1\73\1\0\10\262\2\103\10\0"+
    "\1\104\1\105\1\106\1\157\13\0\1\105\1\106\1\157"+
    "\35\0\1\73\1\0\10\263\2\103\10\0\1\104\1\105"+
    "\1\106\1\157\13\0\1\105\1\106\1\157\37\0\12\264"+
    "\6\0\5\264\1\214\11\0\4\264\1\214\35\0\1\73"+
    "\1\0\10\265\2\103\10\0\1\104\1\105\1\106\1\157"+
    "\13\0\1\105\1\106\1\157\35\0\1\73\1\0\10\266"+
    "\2\103\10\0\1\104\1\105\1\106\1\157\13\0\1\105"+
    "\1\106\1\157\37\0\12\267\6\0\5\267\1\214\11\0"+
    "\4\267\1\214\35\0\1\73\1\0\10\270\2\103\10\0"+
    "\1\104\1\105\1\106\1\157\13\0\1\105\1\106\1\157"+
    "\35\0\1\73\1\0\10\271\2\103\10\0\1\104\1\105"+
    "\1\106\1\157\13\0\1\105\1\106\1\157\37\0\12\272"+
    "\6\0\5\272\1\214\11\0\4\272\1\214\35\0\1\73"+
    "\1\0\10\273\2\103\10\0\1\104\1\105\1\106\1\157"+
    "\13\0\1\105\1\106\1\157\35\0\1\73\1\0\10\274"+
    "\2\103\10\0\1\104\1\105\1\106\1\157\13\0\1\105"+
    "\1\106\1\157\37\0\12\275\6\0\5\275\1\214\11\0"+
    "\4\275\1\214\35\0\1\73\1\0\10\276\2\103\10\0"+
    "\1\104\1\105\1\106\1\157\13\0\1\105\1\106\1\157"+
    "\35\0\1\73\1\0\10\277\2\103\10\0\1\104\1\105"+
    "\1\106\1\157\13\0\1\105\1\106\1\157\37\0\12\300"+
    "\6\0\5\300\1\214\11\0\4\300\1\214\35\0\1\73"+
    "\1\0\10\301\2\103\10\0\1\104\1\105\1\106\1\157"+
    "\13\0\1\105\1\106\1\157\37\0\12\302\6\0\5\302"+
    "\1\214\11\0\4\302\1\214\35\0\1\73\1\0\10\303"+
    "\2\103\10\0\1\104\1\105\1\106\1\157\13\0\1\105"+
    "\1\106\1\157\64\0\1\214\15\0\1\214\35\0\1\73"+
    "\1\0\10\304\2\103\10\0\1\104\1\105\1\106\1\157"+
    "\13\0\1\105\1\106\1\157\35\0\1\73\1\0\10\305"+
    "\2\103\10\0\1\104\1\105\1\106\1\157\13\0\1\105"+
    "\1\106\1\157\35\0\1\73\1\0\10\306\2\103\10\0"+
    "\1\104\1\105\1\106\1\157\13\0\1\105\1\106\1\157"+
    "\35\0\1\73\1\0\12\103\10\0\1\104\1\105\1\106"+
    "\1\157\13\0\1\105\1\106\1\157\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8777];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\2\11\2\1\1\11\3\1\3\11\2\1\1\11"+
    "\5\1\2\11\3\1\1\11\2\1\2\11\3\1\1\11"+
    "\1\1\2\11\1\1\1\11\1\1\1\11\2\1\1\11"+
    "\2\1\10\11\1\0\1\11\1\1\1\0\1\1\1\11"+
    "\5\1\1\11\1\0\2\11\1\0\1\1\3\11\3\1"+
    "\1\11\2\1\5\11\2\1\7\11\12\1\2\0\1\11"+
    "\1\1\1\11\2\1\1\0\3\1\2\11\5\1\4\11"+
    "\2\0\6\11\1\0\2\1\1\11\1\1\1\11\3\1"+
    "\1\0\4\1\1\0\3\1\1\0\3\1\1\0\3\1"+
    "\1\0\3\1\1\0\3\1\1\11\2\1\1\0\2\1"+
    "\1\0\2\1\1\0\2\1\1\0\2\1\1\0\2\1"+
    "\1\0\2\1\1\0\1\1\1\0\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[198];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  private StringBuilder string = new StringBuilder();
  private int columnStringStart = 0;
  private long charStringStart = 0;
  private File parentFile = null;

  private LexSymbol symbol(int type) {
    return new LexSymbol(parentFile, type, yyline, yycolumn, yychar, yylength());
  }

  public LexSymbol next(){
      try{
          return next_token();
      }catch (Exception e){
          throw new RuntimeException(e);
      }
  }

  public boolean hasNext(){
      return !yyatEOF();
  }

  private LexSymbol symbol(int type, Object value) {
    return new LexSymbol(parentFile, type, yyline, yycolumn, yychar,yylength(), value);
  }

    private LexSymbol symbol(int type, int line, int column, long charPos, int size, Object value) {
      return new LexSymbol(parentFile, type, line, column, charPos, size, value);
    }

  public AssemblerScanner(java.io.Reader in, File parentFile) {
    this(in);
    this.parentFile = parentFile;
  }

  

  /**
   * assumes correct representation of a long value for
   * specified radix in scanner buffer from <code>start</code>
   * to <code>end</code>
   */
  private long parseLong(int start, int end, int radix) {
    long result = 0;
    long digit;

    for (int i = start; i < end; i++) {
      digit  = Character.digit(yycharat(i),radix);
      result*= radix;
      result+= digit;
    }

    return result;
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AssemblerScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public LexSymbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return symbol(EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new RuntimeException("Illegal character \""+yytext()+
                                                              "\" at line "+(yyline + 1)+", column "+(yycolumn + 1));
            }
            // fall through
          case 90: break;
          case 2:
            { return symbol(WHITESPACE);
            }
            // fall through
          case 91: break;
          case 3:
            { return symbol(LINE_TERMINATOR);
            }
            // fall through
          case 92: break;
          case 4:
            { return symbol(NOT);
            }
            // fall through
          case 93: break;
          case 5:
            { yybegin(STRING); string.setLength(0); columnStringStart = yycolumn; charStringStart = yychar;
            }
            // fall through
          case 94: break;
          case 6:
            { return symbol(IDENTIFIER, yytext());
            }
            // fall through
          case 95: break;
          case 7:
            { return symbol(MOD);
            }
            // fall through
          case 96: break;
          case 8:
            { return symbol(AND);
            }
            // fall through
          case 97: break;
          case 9:
            { yybegin(CHARLITERAL);
            }
            // fall through
          case 98: break;
          case 10:
            { return symbol(LPAREN);
            }
            // fall through
          case 99: break;
          case 11:
            { return symbol(RPAREN);
            }
            // fall through
          case 100: break;
          case 12:
            { return symbol(MULT);
            }
            // fall through
          case 101: break;
          case 13:
            { return symbol(PLUS);
            }
            // fall through
          case 102: break;
          case 14:
            { return symbol(COMMA);
            }
            // fall through
          case 103: break;
          case 15:
            { return symbol(MINUS);
            }
            // fall through
          case 104: break;
          case 16:
            { return symbol(DOT);
            }
            // fall through
          case 105: break;
          case 17:
            { return symbol(DIV);
            }
            // fall through
          case 106: break;
          case 18:
            { return symbol(INTEGER_LITERAL, Integer.valueOf(yytext()));
            }
            // fall through
          case 107: break;
          case 19:
            { return symbol(COLON);
            }
            // fall through
          case 108: break;
          case 20:
            { return symbol(SEMICOLON);
            }
            // fall through
          case 109: break;
          case 21:
            { return symbol(LT);
            }
            // fall through
          case 110: break;
          case 22:
            { return symbol(EQ);
            }
            // fall through
          case 111: break;
          case 23:
            { return symbol(GT);
            }
            // fall through
          case 112: break;
          case 24:
            { return symbol(QUESTION);
            }
            // fall through
          case 113: break;
          case 25:
            { return symbol(LBRACK);
            }
            // fall through
          case 114: break;
          case 26:
            { return symbol(RBRACK);
            }
            // fall through
          case 115: break;
          case 27:
            { return symbol(XOR);
            }
            // fall through
          case 116: break;
          case 28:
            { return symbol(LBRACE);
            }
            // fall through
          case 117: break;
          case 29:
            { return symbol(OR);
            }
            // fall through
          case 118: break;
          case 30:
            { return symbol(RBRACE);
            }
            // fall through
          case 119: break;
          case 31:
            { return symbol(COMP);
            }
            // fall through
          case 120: break;
          case 32:
            { string.append( yytext() );
            }
            // fall through
          case 121: break;
          case 33:
            { throw new RuntimeException("Unterminated string at end of line");
            }
            // fall through
          case 122: break;
          case 34:
            { yybegin(YYINITIAL); return symbol(STRING_LITERAL, yyline, columnStringStart, charStringStart, yycolumn - columnStringStart + 1 , string.toString());
            }
            // fall through
          case 123: break;
          case 35:
            { throw new RuntimeException("Unterminated character literal at end of line");
            }
            // fall through
          case 124: break;
          case 36:
            { return symbol(NOTEQ);
            }
            // fall through
          case 125: break;
          case 37:
            { return symbol(MODEQ);
            }
            // fall through
          case 126: break;
          case 38:
            { return symbol(ANDAND);
            }
            // fall through
          case 127: break;
          case 39:
            { return symbol(ANDEQ);
            }
            // fall through
          case 128: break;
          case 40:
            { return symbol(MULTEQ);
            }
            // fall through
          case 129: break;
          case 41:
            { return symbol(PLUSPLUS);
            }
            // fall through
          case 130: break;
          case 42:
            { return symbol(PLUSEQ);
            }
            // fall through
          case 131: break;
          case 43:
            { return symbol(MINUSMINUS);
            }
            // fall through
          case 132: break;
          case 44:
            { return symbol(MINUSEQ);
            }
            // fall through
          case 133: break;
          case 45:
            { return symbol(FLOATING_POINT_LITERAL, new Double(yytext()));
            }
            // fall through
          case 134: break;
          case 46:
            { /* ignore */
            }
            // fall through
          case 135: break;
          case 47:
            { return symbol(DIVEQ);
            }
            // fall through
          case 136: break;
          case 48:
            { return symbol(INTEGER_LITERAL, Integer.valueOf((int) parseLong(0, yylength(), 8)));
            }
            // fall through
          case 137: break;
          case 49:
            { return symbol(FLOATING_POINT_LITERAL, new Double(yytext().substring(0,yylength()-1)));
            }
            // fall through
          case 138: break;
          case 50:
            { return symbol(FLOATING_POINT_LITERAL, new Float(yytext().substring(0,yylength()-1)));
            }
            // fall through
          case 139: break;
          case 51:
            { return symbol(INTEGER_LITERAL, new Long(yytext().substring(0,yylength()-1)));
            }
            // fall through
          case 140: break;
          case 52:
            { return symbol(LSHIFT);
            }
            // fall through
          case 141: break;
          case 53:
            { return symbol(LTEQ);
            }
            // fall through
          case 142: break;
          case 54:
            { return symbol(EQEQ);
            }
            // fall through
          case 143: break;
          case 55:
            { return symbol(GTEQ);
            }
            // fall through
          case 144: break;
          case 56:
            { return symbol(RSHIFT);
            }
            // fall through
          case 145: break;
          case 57:
            { return symbol(XOREQ);
            }
            // fall through
          case 146: break;
          case 58:
            { return symbol(OREQ);
            }
            // fall through
          case 147: break;
          case 59:
            { return symbol(OROR);
            }
            // fall through
          case 148: break;
          case 60:
            { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
            }
            // fall through
          case 149: break;
          case 61:
            { string.append( '\"' );
            }
            // fall through
          case 150: break;
          case 62:
            { string.append( '\'' );
            }
            // fall through
          case 151: break;
          case 63:
            { char val = (char) Integer.parseInt(yytext().substring(1),8);
                        				   string.append( val );
            }
            // fall through
          case 152: break;
          case 64:
            { string.append( '\\' );
            }
            // fall through
          case 153: break;
          case 65:
            { string.append( '\b' );
            }
            // fall through
          case 154: break;
          case 66:
            { string.append( '\f' );
            }
            // fall through
          case 155: break;
          case 67:
            { string.append( '\n' );
            }
            // fall through
          case 156: break;
          case 68:
            { string.append( '\r' );
            }
            // fall through
          case 157: break;
          case 69:
            { string.append( '\t' );
            }
            // fall through
          case 158: break;
          case 70:
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, yyline, yycolumn - 1, yychar - 1, yylength() + 1, yytext().charAt(0));
            }
            // fall through
          case 159: break;
          case 71:
            { return symbol(INTEGER_LITERAL, new Long(parseLong(0, yylength()-1, 8)));
            }
            // fall through
          case 160: break;
          case 72:
            { return symbol(INTEGER_LITERAL, Integer.valueOf((int) parseLong(2, yylength(), 16)));
            }
            // fall through
          case 161: break;
          case 73:
            { return symbol(LSHIFTEQ);
            }
            // fall through
          case 162: break;
          case 74:
            { return symbol(RSHIFTEQ);
            }
            // fall through
          case 163: break;
          case 75:
            { return symbol(URSHIFT);
            }
            // fall through
          case 164: break;
          case 76:
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, yyline, yycolumn - 1, yychar - 1, yylength() + 1, '\"');
            }
            // fall through
          case 165: break;
          case 77:
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, yyline, yycolumn - 1, yychar - 1, yylength() + 1, '\'');
            }
            // fall through
          case 166: break;
          case 78:
            { yybegin(YYINITIAL);
			                              int val = Integer.parseInt(yytext().substring(1,yylength()-1),8);
			                            return symbol(CHARACTER_LITERAL, yyline, yycolumn - 1, yychar - 1, yylength() + 1, (char)val);
            }
            // fall through
          case 167: break;
          case 79:
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, yyline, yycolumn - 1, yychar - 1, yylength() + 1, '\\');
            }
            // fall through
          case 168: break;
          case 80:
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, yyline, yycolumn - 1, yychar - 1, yylength() + 1, '\b');
            }
            // fall through
          case 169: break;
          case 81:
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, yyline, yycolumn - 1, yychar - 1, yylength() + 1, '\f');
            }
            // fall through
          case 170: break;
          case 82:
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, yyline, yycolumn - 1, yychar - 1, yylength() + 1, '\n');
            }
            // fall through
          case 171: break;
          case 83:
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, yyline, yycolumn - 1, yychar - 1, yylength() + 1, '\r');
            }
            // fall through
          case 172: break;
          case 84:
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, yyline, yycolumn - 1, yychar - 1, yylength() + 1, '\t');
            }
            // fall through
          case 173: break;
          case 85:
            { return symbol(INTEGER_LITERAL, new Long(parseLong(2, yylength()-1, 16)));
            }
            // fall through
          case 174: break;
          case 86:
            { return symbol(URSHIFTEQ);
            }
            // fall through
          case 175: break;
          case 87:
            { return symbol(BOOLEAN_LITERAL, true);
            }
            // fall through
          case 176: break;
          case 88:
            { return symbol(BOOLEAN_LITERAL, false);
            }
            // fall through
          case 177: break;
          case 89:
            { return symbol(INTEGER_LITERAL, Integer.valueOf(Integer.MIN_VALUE));
            }
            // fall through
          case 178: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
